version: '3'
services:
  api:
    container_name: api
    build: .
    # context: .
    # env_file:
    #   - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    # command: npm run start:dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      # POSTGRES_DB: 'habrdb'
      # POSTGRES_USER: 'habrpguser'
      # POSTGRES_PASSWORD: 'pgpwd4habr'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
