version: '3'
services:
  postgres:
    restart: always
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    restart: always
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

  api:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - /app/node_modules
      - .:/app

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
