version: '3'
services:
  postgres:
    restart: always
    image: postgres:15.1
    networks:
      - my-net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_directory=/var/lib/postgresql/data/log',
        '-c',
        'log_filename=postgres.log',
        '-c',
        'log_statement=all',
      ]

  # pgadmin:
  #   restart: always
  #   image: dpage/pgadmin4:6.18
  #   networks:
  #     - my-net
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - .env

  # adminer:
  #   restart: always
  #   networks:
  #     - my-net
  #   image: adminer
  #   ports:
  #     - '8080:8080'

  app:
    restart: always
    build: ./
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - my-net
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - postgres

networks:
  my-net:
    driver: bridge

volumes:
  postgres_data:
