version: '3'
services:
  postgres:
    restart: always
    image: postgres:15.1
    networks:
      - my-net
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env

  # pgadmin:
  #   restart: always
  #   image: dpage/pgadmin4:6.18
  #   networks:
  #     - my-net
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - .env

  adminer:
    networks:
      - my-net
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # api:
  #   restart: always
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my-net
  #   volumes:
  #     - /app/node_modules
  #     - .:/app

networks:
  my-net:
    driver: bridge

volumes:
  postgres_data:
